### PR TITLE
PSORG Overhaul PR

### PR DESCRIPTION
**Pull request by Jump-Suit**
This PR introduces restructuring of the MUIS, MAS, MLS, MPS, and DME startup sequences respectively to reflect advancements in the configs, and better verbose info.

Numerous new packets have been added and introduced.

Added support for Pre-Medius 1.50 titles

Code organization has been done for cleaner reading.

Review needed.

### CODE REVIEW

**Comment by Dnawrkshp** [comment]
@Jump-Suit Thanks for the PR. I'm running into some issues testing this from a fresh clone. Are you able to make a fresh clone of your repo/this PR and confirm that everything runs and builds correctly?

My issue is that the files [here](https://github.com/Jump-Suit/horizon-server/blob/master/RT.Models/Lobby/MediusSessionBegin1Request.cs) and [here](https://github.com/Jump-Suit/horizon-server/blob/master/RT.Models/Lobby/MediusSetLocalizationParamsResponse.cs) are still referencing the old ```NetMessageTypes``` enum.

Also ```SetLocalizationParamsResponse``` seems to be missing from the enum ```MediusLobbyMessageIds```.

**Review by Dnawrkshp — CHANGES_REQUESTED** [review]
Please make the use of a ```config/``` folder consistent across all binaries. Or move Server.Medius's ```config.json``` file back into the root of the running application.

List of configuration files and whether or not they are in a config folder.

| Project  | File | In config folder |
| ------------- | ------------- | ------------- |
| Server.Medius  | config.json | <ul><li>- [x] </li></ul> |
| Server.Medius  | db.config.json | <ul><li>- [ ] </li></ul> |
| Server.Dme | config.json | <ul><li>- [ ] </li></ul> |
| Server.UniverseInformation | config.json | <ul><li>- [ ] </li></ul> |
| Server.NAT | config.json | <ul><li>- [ ] </li></ul> |

**Comment by Jump-Suit** [comment]
PRed changed for what was requested.
The details are in the commit to address more of what you requested. 

For games that don't use SERVER_ECHO there exists a `ServerEchoUnsupported` config value, this still needs work to disable timeouts for clients that aren't capable of handling SERVER_ECHO!

Additionally, many appIds are implemented per game case. If this breaks support for any of the PS2 Ratchet games let me know.

**Comment by Jump-Suit** [comment]
Due to inactivity with this, I will unfortunately be closing this PR and removing the github repo for this. 
Thanks for looking.

**Pull request closed without merging**
